/*
 * Copyright (C) 2025 eccentric_nz
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package me.eccentric_nz.TARDIS.enumeration;

/**
 * @author eccentric_nz
 */
public enum Storage {

    AREA("Area Storage", "areas", """
            rO0ABXcEAAAANnNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw
            dAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi
            bGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj
            dDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA
            BnQAAj09dAALRGF0YVZlcnNpb250AAJpZHQABWNvdW50dAAKY29tcG9uZW50c3QADnNjaGVtYV92
            ZXJzaW9udXEAfgAGAAAABnQAHm9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1TdGFja3NyABFqYXZh
            LmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0L
            lOCLAgAAeHAAABFYdAAabWluZWNyYWZ0Om11c2ljX2Rpc2NfY2hpcnBzcQB+ABAAAAABc3IAF2ph
            dmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nlc3NPcmRlcnhyABFqYXZhLnV0
            aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9sZHhwP0AAAAAAAAx3
            CAAAABAAAAACdAAVbWluZWNyYWZ0OmN1c3RvbV9uYW1ldAAHIlNhdmVzInQAG21pbmVjcmFmdDpj
            dXN0b21fbW9kZWxfZGF0YXQAF3tmbG9hdHM6WzEuMDAwMDAwMUU3Zl19eABxAH4AFHNxAH4AAHNx
            AH4AA3VxAH4ABgAAAAZxAH4ACHEAfgAJcQB+AApxAH4AC3EAfgAMcQB+AA11cQB+AAYAAAAGcQB+
            AA9zcQB+ABAAABFYdAAbbWluZWNyYWZ0Om11c2ljX2Rpc2NfYmxvY2tzcQB+ABRzcQB+ABU/QAAA
            AAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAciQXJlYXMidAAbbWluZWNy
            YWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAAXe2Zsb2F0czpbMS4wMDAwMDAxRTdmXX14AHEAfgAUc3EA
            fgAAc3EAfgADdXEAfgAGAAAABnEAfgAIcQB+AAlxAH4ACnEAfgALcQB+AAxxAH4ADXVxAH4ABgAA
            AAZxAH4AD3NxAH4AEAAAEVh0ABltaW5lY3JhZnQ6bXVzaWNfZGlzY193YWl0cQB+ABRzcQB+ABU/
            QAAAAAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAkiUGxheWVycyJ0ABtt
            aW5lY3JhZnQ6Y3VzdG9tX21vZGVsX2RhdGF0ABd7ZmxvYXRzOlsxLjAwMDAwMDFFN2ZdfXgAcQB+
            ABRzcQB+AABzcQB+AAN1cQB+AAYAAAAGcQB+AAhxAH4ACXEAfgAKcQB+AAtxAH4ADHEAfgANdXEA
            fgAGAAAABnEAfgAPc3EAfgAQAAARWHQAGG1pbmVjcmFmdDptdXNpY19kaXNjX2NhdHEAfgAUc3EA
            fgAVP0AAAAAAAAx3CAAAABAAAAACdAAVbWluZWNyYWZ0OmN1c3RvbV9uYW1ldAAIIkJpb21lcyJ0
            ABttaW5lY3JhZnQ6Y3VzdG9tX21vZGVsX2RhdGF0ABd7ZmxvYXRzOlsxLjAwMDAwMDFFN2ZdfXgA
            cQB+ABRzcQB+AABzcQB+AAN1cQB+AAYAAAAGcQB+AAhxAH4ACXEAfgAKcQB+AAtxAH4ADHEAfgAN
            dXEAfgAGAAAABnEAfgAPc3EAfgAQAAARWHQAGW1pbmVjcmFmdDptdXNpY19kaXNjX21hbGxxAH4A
            FHNxAH4AFT9AAAAAAAAMdwgAAAAQAAAAAnQAFW1pbmVjcmFmdDpjdXN0b21fbmFtZXQACSJQcmVz
            ZXRzInQAG21pbmVjcmFmdDpjdXN0b21fbW9kZWxfZGF0YXQAF3tmbG9hdHM6WzEuMDAwMDAwMUU3
            Zl19eABxAH4AFHNxAH4AAHNxAH4AA3VxAH4ABgAAAAZxAH4ACHEAfgAJcQB+AApxAH4AC3EAfgAM
            cQB+AA11cQB+AAYAAAAGcQB+AA9zcQB+ABAAABFYdAAYbWluZWNyYWZ0Omdsb3dzdG9uZV9kdXN0
            cQB+ABRzcQB+ABU/QAAAAAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAoi
            Q2lyY3VpdHMidAAbbWluZWNyYWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAARe2Zsb2F0czpbMTMwLjBm
            XX14AHEAfgAUcHBwcHBwcHBwcHBwcHBwcHNxAH4AAHNxAH4AA3VxAH4ABgAAAAZxAH4ACHEAfgAJ
            cQB+AApxAH4AC3EAfgAMcQB+AA11cQB+AAYAAAAGcQB+AA9zcQB+ABAAABFYdAAbbWluZWNyYWZ0
            Om11c2ljX2Rpc2NfYmxvY2tzcQB+ABRzcQB+ABU/QAAAAAAADHcIAAAAEAAAAAJ0ABVtaW5lY3Jh
            ZnQ6Y3VzdG9tX25hbWV0AAciQXJlYXMidAAbbWluZWNyYWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAAX
            e2Zsb2F0czpbMS4wMDAwMDAxRTdmXX14AHEAfgAUcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBw
            cHBwcA==
            """),

    BIOME_1("Biome Storage 1", "biomes_one", """
            rO0ABXcEAAAANnNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw
            dAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi
            bGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj
            dDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA
            BnQAAj09dAALRGF0YVZlcnNpb250AAJpZHQABWNvdW50dAAKY29tcG9uZW50c3QADnNjaGVtYV92
            ZXJzaW9udXEAfgAGAAAABnQAHm9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1TdGFja3NyABFqYXZh
            LmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0L
            lOCLAgAAeHAAABFYdAAabWluZWNyYWZ0Om11c2ljX2Rpc2NfY2hpcnBzcQB+ABAAAAABc3IAF2ph
            dmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nlc3NPcmRlcnhyABFqYXZhLnV0
            aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9sZHhwP0AAAAAAAAx3
            CAAAABAAAAACdAAVbWluZWNyYWZ0OmN1c3RvbV9uYW1ldAAHIlNhdmVzInQAG21pbmVjcmFmdDpj
            dXN0b21fbW9kZWxfZGF0YXQAF3tmbG9hdHM6WzEuMDAwMDAwMUU3Zl19eABxAH4AFHNxAH4AAHNx
            AH4AA3VxAH4ABgAAAAZxAH4ACHEAfgAJcQB+AApxAH4AC3EAfgAMcQB+AA11cQB+AAYAAAAGcQB+
            AA9zcQB+ABAAABFYdAAbbWluZWNyYWZ0Om11c2ljX2Rpc2NfYmxvY2tzcQB+ABRzcQB+ABU/QAAA
            AAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAciQXJlYXMidAAbbWluZWNy
            YWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAAXe2Zsb2F0czpbMS4wMDAwMDAxRTdmXX14AHEAfgAUc3EA
            fgAAc3EAfgADdXEAfgAGAAAABnEAfgAIcQB+AAlxAH4ACnEAfgALcQB+AAxxAH4ADXVxAH4ABgAA
            AAZxAH4AD3NxAH4AEAAAEVh0ABltaW5lY3JhZnQ6bXVzaWNfZGlzY193YWl0cQB+ABRzcQB+ABU/
            QAAAAAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAkiUGxheWVycyJ0ABtt
            aW5lY3JhZnQ6Y3VzdG9tX21vZGVsX2RhdGF0ABd7ZmxvYXRzOlsxLjAwMDAwMDFFN2ZdfXgAcQB+
            ABRzcQB+AABzcQB+AAN1cQB+AAYAAAAGcQB+AAhxAH4ACXEAfgAKcQB+AAtxAH4ADHEAfgANdXEA
            fgAGAAAABnEAfgAPc3EAfgAQAAARWHQAGG1pbmVjcmFmdDptdXNpY19kaXNjX2NhdHEAfgAUc3EA
            fgAVP0AAAAAAAAx3CAAAABAAAAACdAAVbWluZWNyYWZ0OmN1c3RvbV9uYW1ldAAIIkJpb21lcyJ0
            ABttaW5lY3JhZnQ6Y3VzdG9tX21vZGVsX2RhdGF0ABd7ZmxvYXRzOlsxLjAwMDAwMDFFN2ZdfXgA
            cQB+ABRzcQB+AABzcQB+AAN1cQB+AAYAAAAGcQB+AAhxAH4ACXEAfgAKcQB+AAtxAH4ADHEAfgAN
            dXEAfgAGAAAABnEAfgAPc3EAfgAQAAARWHQAGW1pbmVjcmFmdDptdXNpY19kaXNjX21hbGxxAH4A
            FHNxAH4AFT9AAAAAAAAMdwgAAAAQAAAAAnQAFW1pbmVjcmFmdDpjdXN0b21fbmFtZXQACSJQcmVz
            ZXRzInQAG21pbmVjcmFmdDpjdXN0b21fbW9kZWxfZGF0YXQAF3tmbG9hdHM6WzEuMDAwMDAwMUU3
            Zl19eABxAH4AFHNxAH4AAHNxAH4AA3VxAH4ABgAAAAZxAH4ACHEAfgAJcQB+AApxAH4AC3EAfgAM
            cQB+AA11cQB+AAYAAAAGcQB+AA9zcQB+ABAAABFYdAAYbWluZWNyYWZ0Omdsb3dzdG9uZV9kdXN0
            cQB+ABRzcQB+ABU/QAAAAAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAoi
            Q2lyY3VpdHMidAAbbWluZWNyYWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAARe2Zsb2F0czpbMTMwLjBm
            XX14AHEAfgAUcHBwcHBwcHBwcHBwcHBwcHNxAH4AAHNxAH4AA3VxAH4ABgAAAAZxAH4ACHEAfgAJ
            cQB+AApxAH4AC3EAfgAMcQB+AA11cQB+AAYAAAAGcQB+AA9zcQB+ABAAABFYdAAYbWluZWNyYWZ0
            Om11c2ljX2Rpc2NfY2F0cQB+ABRzcQB+ABU/QAAAAAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6
            Y3VzdG9tX25hbWV0AAoiQmlvbWVzIDEidAAbbWluZWNyYWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAAX
            e2Zsb2F0czpbMS4wMDAwMDAxRTdmXX14AHEAfgAUcHBwc3EAfgAAc3EAfgADdXEAfgAGAAAABnEA
            fgAIcQB+AAlxAH4ACnEAfgALcQB+AAxxAH4ADXVxAH4ABgAAAAZxAH4AD3NxAH4AEAAAEVh0AA5t
            aW5lY3JhZnQ6Ym93bHEAfgAUc3EAfgAVP0AAAAAAAAx3CAAAABAAAAACdAAVbWluZWNyYWZ0OmN1
            c3RvbV9uYW1ldAALIk5leHQgUGFnZSJ0ABttaW5lY3JhZnQ6Y3VzdG9tX21vZGVsX2RhdGF0ABB7
            ZmxvYXRzOls4Ni4wZl19eABxAH4AFHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcA==
            """),

    BIOME_2("Biome Storage 2", "biomes_two", """
            rO0ABXcEAAAANnNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw
            dAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi
            bGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj
            dDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA
            BnQAAj09dAALRGF0YVZlcnNpb250AAJpZHQABWNvdW50dAAKY29tcG9uZW50c3QADnNjaGVtYV92
            ZXJzaW9udXEAfgAGAAAABnQAHm9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1TdGFja3NyABFqYXZh
            LmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0L
            lOCLAgAAeHAAABFYdAAabWluZWNyYWZ0Om11c2ljX2Rpc2NfY2hpcnBzcQB+ABAAAAABc3IAF2ph
            dmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nlc3NPcmRlcnhyABFqYXZhLnV0
            aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9sZHhwP0AAAAAAAAx3
            CAAAABAAAAACdAAVbWluZWNyYWZ0OmN1c3RvbV9uYW1ldAAHIlNhdmVzInQAG21pbmVjcmFmdDpj
            dXN0b21fbW9kZWxfZGF0YXQAF3tmbG9hdHM6WzEuMDAwMDAwMUU3Zl19eABxAH4AFHNxAH4AAHNx
            AH4AA3VxAH4ABgAAAAZxAH4ACHEAfgAJcQB+AApxAH4AC3EAfgAMcQB+AA11cQB+AAYAAAAGcQB+
            AA9zcQB+ABAAABFYdAAbbWluZWNyYWZ0Om11c2ljX2Rpc2NfYmxvY2tzcQB+ABRzcQB+ABU/QAAA
            AAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAciQXJlYXMidAAbbWluZWNy
            YWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAAXe2Zsb2F0czpbMS4wMDAwMDAxRTdmXX14AHEAfgAUc3EA
            fgAAc3EAfgADdXEAfgAGAAAABnEAfgAIcQB+AAlxAH4ACnEAfgALcQB+AAxxAH4ADXVxAH4ABgAA
            AAZxAH4AD3NxAH4AEAAAEVh0ABltaW5lY3JhZnQ6bXVzaWNfZGlzY193YWl0cQB+ABRzcQB+ABU/
            QAAAAAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAkiUGxheWVycyJ0ABtt
            aW5lY3JhZnQ6Y3VzdG9tX21vZGVsX2RhdGF0ABd7ZmxvYXRzOlsxLjAwMDAwMDFFN2ZdfXgAcQB+
            ABRzcQB+AABzcQB+AAN1cQB+AAYAAAAGcQB+AAhxAH4ACXEAfgAKcQB+AAtxAH4ADHEAfgANdXEA
            fgAGAAAABnEAfgAPc3EAfgAQAAARWHQAGG1pbmVjcmFmdDptdXNpY19kaXNjX2NhdHEAfgAUc3EA
            fgAVP0AAAAAAAAx3CAAAABAAAAACdAAVbWluZWNyYWZ0OmN1c3RvbV9uYW1ldAAIIkJpb21lcyJ0
            ABttaW5lY3JhZnQ6Y3VzdG9tX21vZGVsX2RhdGF0ABd7ZmxvYXRzOlsxLjAwMDAwMDFFN2ZdfXgA
            cQB+ABRzcQB+AABzcQB+AAN1cQB+AAYAAAAGcQB+AAhxAH4ACXEAfgAKcQB+AAtxAH4ADHEAfgAN
            dXEAfgAGAAAABnEAfgAPc3EAfgAQAAARWHQAGW1pbmVjcmFmdDptdXNpY19kaXNjX21hbGxxAH4A
            FHNxAH4AFT9AAAAAAAAMdwgAAAAQAAAAAnQAFW1pbmVjcmFmdDpjdXN0b21fbmFtZXQACSJQcmVz
            ZXRzInQAG21pbmVjcmFmdDpjdXN0b21fbW9kZWxfZGF0YXQAF3tmbG9hdHM6WzEuMDAwMDAwMUU3
            Zl19eABxAH4AFHNxAH4AAHNxAH4AA3VxAH4ABgAAAAZxAH4ACHEAfgAJcQB+AApxAH4AC3EAfgAM
            cQB+AA11cQB+AAYAAAAGcQB+AA9zcQB+ABAAABFYdAAYbWluZWNyYWZ0Omdsb3dzdG9uZV9kdXN0
            cQB+ABRzcQB+ABU/QAAAAAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAoi
            Q2lyY3VpdHMidAAbbWluZWNyYWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAARe2Zsb2F0czpbMTMwLjBm
            XX14AHEAfgAUcHBwcHBwcHBwcHBwc3EAfgAAc3EAfgADdXEAfgAGAAAABnEAfgAIcQB+AAlxAH4A
            CnEAfgALcQB+AAxxAH4ADXVxAH4ABgAAAAZxAH4AD3NxAH4AEAAAEVh0AA5taW5lY3JhZnQ6Ym93
            bHEAfgAUc3EAfgAVP0AAAAAAAAx3CAAAABAAAAACdAAVbWluZWNyYWZ0OmN1c3RvbV9uYW1ldAAP
            IlByZXZpb3VzIFBhZ2UidAAbbWluZWNyYWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAAQe2Zsb2F0czpb
            ODcuMGZdfXgAcQB+ABRwcHBzcQB+AABzcQB+AAN1cQB+AAYAAAAGcQB+AAhxAH4ACXEAfgAKcQB+
            AAtxAH4ADHEAfgANdXEAfgAGAAAABnEAfgAPc3EAfgAQAAARWHQAGG1pbmVjcmFmdDptdXNpY19k
            aXNjX2NhdHEAfgAUc3EAfgAVP0AAAAAAAAx3CAAAABAAAAACdAAVbWluZWNyYWZ0OmN1c3RvbV9u
            YW1ldAAKIkJpb21lcyAyInQAG21pbmVjcmFmdDpjdXN0b21fbW9kZWxfZGF0YXQAF3tmbG9hdHM6
            WzEuMDAwMDAwMUU3Zl19eABxAH4AFHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHA=
            """),

    CIRCUIT("Circuit Storage", "circuits", """
            rO0ABXcEAAAANnNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw
            dAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi
            bGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj
            dDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA
            BnQAAj09dAALRGF0YVZlcnNpb250AAJpZHQABWNvdW50dAAKY29tcG9uZW50c3QADnNjaGVtYV92
            ZXJzaW9udXEAfgAGAAAABnQAHm9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1TdGFja3NyABFqYXZh
            LmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0L
            lOCLAgAAeHAAABFYdAAabWluZWNyYWZ0Om11c2ljX2Rpc2NfY2hpcnBzcQB+ABAAAAABc3IAF2ph
            dmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nlc3NPcmRlcnhyABFqYXZhLnV0
            aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9sZHhwP0AAAAAAAAx3
            CAAAABAAAAACdAAVbWluZWNyYWZ0OmN1c3RvbV9uYW1ldAAHIlNhdmVzInQAG21pbmVjcmFmdDpj
            dXN0b21fbW9kZWxfZGF0YXQAF3tmbG9hdHM6WzEuMDAwMDAwMUU3Zl19eABxAH4AFHNxAH4AAHNx
            AH4AA3VxAH4ABgAAAAZxAH4ACHEAfgAJcQB+AApxAH4AC3EAfgAMcQB+AA11cQB+AAYAAAAGcQB+
            AA9zcQB+ABAAABFYdAAbbWluZWNyYWZ0Om11c2ljX2Rpc2NfYmxvY2tzcQB+ABRzcQB+ABU/QAAA
            AAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAciQXJlYXMidAAbbWluZWNy
            YWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAAXe2Zsb2F0czpbMS4wMDAwMDAxRTdmXX14AHEAfgAUc3EA
            fgAAc3EAfgADdXEAfgAGAAAABnEAfgAIcQB+AAlxAH4ACnEAfgALcQB+AAxxAH4ADXVxAH4ABgAA
            AAZxAH4AD3NxAH4AEAAAEVh0ABltaW5lY3JhZnQ6bXVzaWNfZGlzY193YWl0cQB+ABRzcQB+ABU/
            QAAAAAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAkiUGxheWVycyJ0ABtt
            aW5lY3JhZnQ6Y3VzdG9tX21vZGVsX2RhdGF0ABd7ZmxvYXRzOlsxLjAwMDAwMDFFN2ZdfXgAcQB+
            ABRzcQB+AABzcQB+AAN1cQB+AAYAAAAGcQB+AAhxAH4ACXEAfgAKcQB+AAtxAH4ADHEAfgANdXEA
            fgAGAAAABnEAfgAPc3EAfgAQAAARWHQAGG1pbmVjcmFmdDptdXNpY19kaXNjX2NhdHEAfgAUc3EA
            fgAVP0AAAAAAAAx3CAAAABAAAAACdAAVbWluZWNyYWZ0OmN1c3RvbV9uYW1ldAAIIkJpb21lcyJ0
            ABttaW5lY3JhZnQ6Y3VzdG9tX21vZGVsX2RhdGF0ABd7ZmxvYXRzOlsxLjAwMDAwMDFFN2ZdfXgA
            cQB+ABRzcQB+AABzcQB+AAN1cQB+AAYAAAAGcQB+AAhxAH4ACXEAfgAKcQB+AAtxAH4ADHEAfgAN
            dXEAfgAGAAAABnEAfgAPc3EAfgAQAAARWHQAGW1pbmVjcmFmdDptdXNpY19kaXNjX21hbGxxAH4A
            FHNxAH4AFT9AAAAAAAAMdwgAAAAQAAAAAnQAFW1pbmVjcmFmdDpjdXN0b21fbmFtZXQACSJQcmVz
            ZXRzInQAG21pbmVjcmFmdDpjdXN0b21fbW9kZWxfZGF0YXQAF3tmbG9hdHM6WzEuMDAwMDAwMUU3
            Zl19eABxAH4AFHNxAH4AAHNxAH4AA3VxAH4ABgAAAAZxAH4ACHEAfgAJcQB+AApxAH4AC3EAfgAM
            cQB+AA11cQB+AAYAAAAGcQB+AA9zcQB+ABAAABFYdAAYbWluZWNyYWZ0Omdsb3dzdG9uZV9kdXN0
            cQB+ABRzcQB+ABU/QAAAAAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAoi
            Q2lyY3VpdHMidAAbbWluZWNyYWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAARe2Zsb2F0czpbMTMwLjBm
            XX14AHEAfgAUcHBwcHBwcHBwcHBwcHBwcHNxAH4AAHNxAH4AA3VxAH4ABgAAAAZxAH4ACHEAfgAJ
            cQB+AApxAH4AC3EAfgAMcQB+AA11cQB+AAYAAAAGcQB+AA9zcQB+ABAAABFYdAAYbWluZWNyYWZ0
            Omdsb3dzdG9uZV9kdXN0cQB+ABRzcQB+ABU/QAAAAAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6
            Y3VzdG9tX25hbWV0AAoiQ2lyY3VpdHMidAAbbWluZWNyYWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAAR
            e2Zsb2F0czpbMTMwLjBmXX14AHEAfgAUcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcA==
            """),

    PLAYER("Player Storage", "players", """
            rO0ABXcEAAAANnNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw
            dAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi
            bGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj
            dDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA
            BnQAAj09dAALRGF0YVZlcnNpb250AAJpZHQABWNvdW50dAAKY29tcG9uZW50c3QADnNjaGVtYV92
            ZXJzaW9udXEAfgAGAAAABnQAHm9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1TdGFja3NyABFqYXZh
            LmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0L
            lOCLAgAAeHAAABFYdAAabWluZWNyYWZ0Om11c2ljX2Rpc2NfY2hpcnBzcQB+ABAAAAABc3IAF2ph
            dmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nlc3NPcmRlcnhyABFqYXZhLnV0
            aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9sZHhwP0AAAAAAAAx3
            CAAAABAAAAACdAAVbWluZWNyYWZ0OmN1c3RvbV9uYW1ldAAHIlNhdmVzInQAG21pbmVjcmFmdDpj
            dXN0b21fbW9kZWxfZGF0YXQAF3tmbG9hdHM6WzEuMDAwMDAwMUU3Zl19eABxAH4AFHNxAH4AAHNx
            AH4AA3VxAH4ABgAAAAZxAH4ACHEAfgAJcQB+AApxAH4AC3EAfgAMcQB+AA11cQB+AAYAAAAGcQB+
            AA9zcQB+ABAAABFYdAAbbWluZWNyYWZ0Om11c2ljX2Rpc2NfYmxvY2tzcQB+ABRzcQB+ABU/QAAA
            AAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAciQXJlYXMidAAbbWluZWNy
            YWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAAXe2Zsb2F0czpbMS4wMDAwMDAxRTdmXX14AHEAfgAUc3EA
            fgAAc3EAfgADdXEAfgAGAAAABnEAfgAIcQB+AAlxAH4ACnEAfgALcQB+AAxxAH4ADXVxAH4ABgAA
            AAZxAH4AD3NxAH4AEAAAEVh0ABltaW5lY3JhZnQ6bXVzaWNfZGlzY193YWl0cQB+ABRzcQB+ABU/
            QAAAAAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAkiUGxheWVycyJ0ABtt
            aW5lY3JhZnQ6Y3VzdG9tX21vZGVsX2RhdGF0ABd7ZmxvYXRzOlsxLjAwMDAwMDFFN2ZdfXgAcQB+
            ABRzcQB+AABzcQB+AAN1cQB+AAYAAAAGcQB+AAhxAH4ACXEAfgAKcQB+AAtxAH4ADHEAfgANdXEA
            fgAGAAAABnEAfgAPc3EAfgAQAAARWHQAGG1pbmVjcmFmdDptdXNpY19kaXNjX2NhdHEAfgAUc3EA
            fgAVP0AAAAAAAAx3CAAAABAAAAACdAAVbWluZWNyYWZ0OmN1c3RvbV9uYW1ldAAIIkJpb21lcyJ0
            ABttaW5lY3JhZnQ6Y3VzdG9tX21vZGVsX2RhdGF0ABd7ZmxvYXRzOlsxLjAwMDAwMDFFN2ZdfXgA
            cQB+ABRzcQB+AABzcQB+AAN1cQB+AAYAAAAGcQB+AAhxAH4ACXEAfgAKcQB+AAtxAH4ADHEAfgAN
            dXEAfgAGAAAABnEAfgAPc3EAfgAQAAARWHQAGW1pbmVjcmFmdDptdXNpY19kaXNjX21hbGxxAH4A
            FHNxAH4AFT9AAAAAAAAMdwgAAAAQAAAAAnQAFW1pbmVjcmFmdDpjdXN0b21fbmFtZXQACSJQcmVz
            ZXRzInQAG21pbmVjcmFmdDpjdXN0b21fbW9kZWxfZGF0YXQAF3tmbG9hdHM6WzEuMDAwMDAwMUU3
            Zl19eABxAH4AFHNxAH4AAHNxAH4AA3VxAH4ABgAAAAZxAH4ACHEAfgAJcQB+AApxAH4AC3EAfgAM
            cQB+AA11cQB+AAYAAAAGcQB+AA9zcQB+ABAAABFYdAAYbWluZWNyYWZ0Omdsb3dzdG9uZV9kdXN0
            cQB+ABRzcQB+ABU/QAAAAAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAoi
            Q2lyY3VpdHMidAAbbWluZWNyYWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAARe2Zsb2F0czpbMTMwLjBm
            XX14AHEAfgAUcHBwcHBwcHBwcHBwcHBwcHNxAH4AAHNxAH4AA3VxAH4ABgAAAAZxAH4ACHEAfgAJ
            cQB+AApxAH4AC3EAfgAMcQB+AA11cQB+AAYAAAAGcQB+AA9zcQB+ABAAABFYdAAZbWluZWNyYWZ0
            Om11c2ljX2Rpc2Nfd2FpdHEAfgAUc3EAfgAVP0AAAAAAAAx3CAAAABAAAAACdAAVbWluZWNyYWZ0
            OmN1c3RvbV9uYW1ldAAJIlBsYXllcnMidAAbbWluZWNyYWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAAX
            e2Zsb2F0czpbMS4wMDAwMDAxRTdmXX14AHEAfgAUcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBw
            cHBwcA==
            """),

    PRESET_1("Preset Storage 1", "presets_one", """
            rO0ABXcEAAAANnNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw
            dAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi
            bGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj
            dDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA
            BnQAAj09dAALRGF0YVZlcnNpb250AAJpZHQABWNvdW50dAAKY29tcG9uZW50c3QADnNjaGVtYV92
            ZXJzaW9udXEAfgAGAAAABnQAHm9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1TdGFja3NyABFqYXZh
            LmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0L
            lOCLAgAAeHAAABFYdAAabWluZWNyYWZ0Om11c2ljX2Rpc2NfY2hpcnBzcQB+ABAAAAABc3IAF2ph
            dmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nlc3NPcmRlcnhyABFqYXZhLnV0
            aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9sZHhwP0AAAAAAAAx3
            CAAAABAAAAACdAAVbWluZWNyYWZ0OmN1c3RvbV9uYW1ldAAHIlNhdmVzInQAG21pbmVjcmFmdDpj
            dXN0b21fbW9kZWxfZGF0YXQAF3tmbG9hdHM6WzEuMDAwMDAwMUU3Zl19eABxAH4AFHNxAH4AAHNx
            AH4AA3VxAH4ABgAAAAZxAH4ACHEAfgAJcQB+AApxAH4AC3EAfgAMcQB+AA11cQB+AAYAAAAGcQB+
            AA9zcQB+ABAAABFYdAAbbWluZWNyYWZ0Om11c2ljX2Rpc2NfYmxvY2tzcQB+ABRzcQB+ABU/QAAA
            AAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAciQXJlYXMidAAbbWluZWNy
            YWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAAXe2Zsb2F0czpbMS4wMDAwMDAxRTdmXX14AHEAfgAUc3EA
            fgAAc3EAfgADdXEAfgAGAAAABnEAfgAIcQB+AAlxAH4ACnEAfgALcQB+AAxxAH4ADXVxAH4ABgAA
            AAZxAH4AD3NxAH4AEAAAEVh0ABltaW5lY3JhZnQ6bXVzaWNfZGlzY193YWl0cQB+ABRzcQB+ABU/
            QAAAAAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAkiUGxheWVycyJ0ABtt
            aW5lY3JhZnQ6Y3VzdG9tX21vZGVsX2RhdGF0ABd7ZmxvYXRzOlsxLjAwMDAwMDFFN2ZdfXgAcQB+
            ABRzcQB+AABzcQB+AAN1cQB+AAYAAAAGcQB+AAhxAH4ACXEAfgAKcQB+AAtxAH4ADHEAfgANdXEA
            fgAGAAAABnEAfgAPc3EAfgAQAAARWHQAGG1pbmVjcmFmdDptdXNpY19kaXNjX2NhdHEAfgAUc3EA
            fgAVP0AAAAAAAAx3CAAAABAAAAACdAAVbWluZWNyYWZ0OmN1c3RvbV9uYW1ldAAIIkJpb21lcyJ0
            ABttaW5lY3JhZnQ6Y3VzdG9tX21vZGVsX2RhdGF0ABd7ZmxvYXRzOlsxLjAwMDAwMDFFN2ZdfXgA
            cQB+ABRzcQB+AABzcQB+AAN1cQB+AAYAAAAGcQB+AAhxAH4ACXEAfgAKcQB+AAtxAH4ADHEAfgAN
            dXEAfgAGAAAABnEAfgAPc3EAfgAQAAARWHQAGW1pbmVjcmFmdDptdXNpY19kaXNjX21hbGxxAH4A
            FHNxAH4AFT9AAAAAAAAMdwgAAAAQAAAAAnQAFW1pbmVjcmFmdDpjdXN0b21fbmFtZXQACSJQcmVz
            ZXRzInQAG21pbmVjcmFmdDpjdXN0b21fbW9kZWxfZGF0YXQAF3tmbG9hdHM6WzEuMDAwMDAwMUU3
            Zl19eABxAH4AFHNxAH4AAHNxAH4AA3VxAH4ABgAAAAZxAH4ACHEAfgAJcQB+AApxAH4AC3EAfgAM
            cQB+AA11cQB+AAYAAAAGcQB+AA9zcQB+ABAAABFYdAAYbWluZWNyYWZ0Omdsb3dzdG9uZV9kdXN0
            cQB+ABRzcQB+ABU/QAAAAAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAoi
            Q2lyY3VpdHMidAAbbWluZWNyYWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAARe2Zsb2F0czpbMTMwLjBm
            XX14AHEAfgAUcHBwcHBwcHBwcHBwcHBwcHNxAH4AAHNxAH4AA3VxAH4ABgAAAAZxAH4ACHEAfgAJ
            cQB+AApxAH4AC3EAfgAMcQB+AA11cQB+AAYAAAAGcQB+AA9zcQB+ABAAABFYdAAZbWluZWNyYWZ0
            Om11c2ljX2Rpc2NfbWFsbHEAfgAUc3EAfgAVP0AAAAAAAAx3CAAAABAAAAACdAAVbWluZWNyYWZ0
            OmN1c3RvbV9uYW1ldAALIlByZXNldHMgMSJ0ABttaW5lY3JhZnQ6Y3VzdG9tX21vZGVsX2RhdGF0
            ABd7ZmxvYXRzOlsxLjAwMDAwMDFFN2ZdfXgAcQB+ABRwcHBzcQB+AABzcQB+AAN1cQB+AAYAAAAG
            cQB+AAhxAH4ACXEAfgAKcQB+AAtxAH4ADHEAfgANdXEAfgAGAAAABnEAfgAPc3EAfgAQAAARWHQA
            Dm1pbmVjcmFmdDpib3dscQB+ABRzcQB+ABU/QAAAAAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6
            Y3VzdG9tX25hbWV0AAsiTmV4dCBQYWdlInQAG21pbmVjcmFmdDpjdXN0b21fbW9kZWxfZGF0YXQA
            EHtmbG9hdHM6Wzg2LjBmXX14AHEAfgAUcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBw
            """),

    PRESET_2("Preset Storage 2", "presets_two", """
            rO0ABXcEAAAANnNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw
            dAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi
            bGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj
            dDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA
            BnQAAj09dAALRGF0YVZlcnNpb250AAJpZHQABWNvdW50dAAKY29tcG9uZW50c3QADnNjaGVtYV92
            ZXJzaW9udXEAfgAGAAAABnQAHm9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1TdGFja3NyABFqYXZh
            LmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0L
            lOCLAgAAeHAAABFYdAAabWluZWNyYWZ0Om11c2ljX2Rpc2NfY2hpcnBzcQB+ABAAAAABc3IAF2ph
            dmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nlc3NPcmRlcnhyABFqYXZhLnV0
            aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9sZHhwP0AAAAAAAAx3
            CAAAABAAAAACdAAVbWluZWNyYWZ0OmN1c3RvbV9uYW1ldAAHIlNhdmVzInQAG21pbmVjcmFmdDpj
            dXN0b21fbW9kZWxfZGF0YXQAF3tmbG9hdHM6WzEuMDAwMDAwMUU3Zl19eABxAH4AFHNxAH4AAHNx
            AH4AA3VxAH4ABgAAAAZxAH4ACHEAfgAJcQB+AApxAH4AC3EAfgAMcQB+AA11cQB+AAYAAAAGcQB+
            AA9zcQB+ABAAABFYdAAbbWluZWNyYWZ0Om11c2ljX2Rpc2NfYmxvY2tzcQB+ABRzcQB+ABU/QAAA
            AAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAciQXJlYXMidAAbbWluZWNy
            YWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAAXe2Zsb2F0czpbMS4wMDAwMDAxRTdmXX14AHEAfgAUc3EA
            fgAAc3EAfgADdXEAfgAGAAAABnEAfgAIcQB+AAlxAH4ACnEAfgALcQB+AAxxAH4ADXVxAH4ABgAA
            AAZxAH4AD3NxAH4AEAAAEVh0ABltaW5lY3JhZnQ6bXVzaWNfZGlzY193YWl0cQB+ABRzcQB+ABU/
            QAAAAAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAkiUGxheWVycyJ0ABtt
            aW5lY3JhZnQ6Y3VzdG9tX21vZGVsX2RhdGF0ABd7ZmxvYXRzOlsxLjAwMDAwMDFFN2ZdfXgAcQB+
            ABRzcQB+AABzcQB+AAN1cQB+AAYAAAAGcQB+AAhxAH4ACXEAfgAKcQB+AAtxAH4ADHEAfgANdXEA
            fgAGAAAABnEAfgAPc3EAfgAQAAARWHQAGG1pbmVjcmFmdDptdXNpY19kaXNjX2NhdHEAfgAUc3EA
            fgAVP0AAAAAAAAx3CAAAABAAAAACdAAVbWluZWNyYWZ0OmN1c3RvbV9uYW1ldAAIIkJpb21lcyJ0
            ABttaW5lY3JhZnQ6Y3VzdG9tX21vZGVsX2RhdGF0ABd7ZmxvYXRzOlsxLjAwMDAwMDFFN2ZdfXgA
            cQB+ABRzcQB+AABzcQB+AAN1cQB+AAYAAAAGcQB+AAhxAH4ACXEAfgAKcQB+AAtxAH4ADHEAfgAN
            dXEAfgAGAAAABnEAfgAPc3EAfgAQAAARWHQAGW1pbmVjcmFmdDptdXNpY19kaXNjX21hbGxxAH4A
            FHNxAH4AFT9AAAAAAAAMdwgAAAAQAAAAAnQAFW1pbmVjcmFmdDpjdXN0b21fbmFtZXQACSJQcmVz
            ZXRzInQAG21pbmVjcmFmdDpjdXN0b21fbW9kZWxfZGF0YXQAF3tmbG9hdHM6WzEuMDAwMDAwMUU3
            Zl19eABxAH4AFHNxAH4AAHNxAH4AA3VxAH4ABgAAAAZxAH4ACHEAfgAJcQB+AApxAH4AC3EAfgAM
            cQB+AA11cQB+AAYAAAAGcQB+AA9zcQB+ABAAABFYdAAYbWluZWNyYWZ0Omdsb3dzdG9uZV9kdXN0
            cQB+ABRzcQB+ABU/QAAAAAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAoi
            Q2lyY3VpdHMidAAbbWluZWNyYWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAARe2Zsb2F0czpbMTMwLjBm
            XX14AHEAfgAUcHBwcHBwcHBwcHBwc3EAfgAAc3EAfgADdXEAfgAGAAAABnEAfgAIcQB+AAlxAH4A
            CnEAfgALcQB+AAxxAH4ADXVxAH4ABgAAAAZxAH4AD3NxAH4AEAAAEVh0AA5taW5lY3JhZnQ6Ym93
            bHEAfgAUc3EAfgAVP0AAAAAAAAx3CAAAABAAAAACdAAVbWluZWNyYWZ0OmN1c3RvbV9uYW1ldAAP
            IlByZXZpb3VzIFBhZ2UidAAbbWluZWNyYWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAAQe2Zsb2F0czpb
            ODcuMGZdfXgAcQB+ABRwcHBzcQB+AABzcQB+AAN1cQB+AAYAAAAGcQB+AAhxAH4ACXEAfgAKcQB+
            AAtxAH4ADHEAfgANdXEAfgAGAAAABnEAfgAPc3EAfgAQAAARWHQAGW1pbmVjcmFmdDptdXNpY19k
            aXNjX21hbGxxAH4AFHNxAH4AFT9AAAAAAAAMdwgAAAAQAAAAAnQAFW1pbmVjcmFmdDpjdXN0b21f
            bmFtZXQACyJQcmVzZXRzIDIidAAbbWluZWNyYWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAAXe2Zsb2F0
            czpbMS4wMDAwMDAxRTdmXX14AHEAfgAUcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcA==
            """),

    SAVE_1("Save Storage 1", "saves_one", """
            rO0ABXcEAAAANnNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw
            dAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi
            bGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj
            dDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA
            BnQAAj09dAALRGF0YVZlcnNpb250AAJpZHQABWNvdW50dAAKY29tcG9uZW50c3QADnNjaGVtYV92
            ZXJzaW9udXEAfgAGAAAABnQAHm9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1TdGFja3NyABFqYXZh
            LmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0L
            lOCLAgAAeHAAABFYdAAabWluZWNyYWZ0Om11c2ljX2Rpc2NfY2hpcnBzcQB+ABAAAAABc3IAF2ph
            dmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nlc3NPcmRlcnhyABFqYXZhLnV0
            aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9sZHhwP0AAAAAAAAx3
            CAAAABAAAAACdAAVbWluZWNyYWZ0OmN1c3RvbV9uYW1ldAAHIlNhdmVzInQAG21pbmVjcmFmdDpj
            dXN0b21fbW9kZWxfZGF0YXQAF3tmbG9hdHM6WzEuMDAwMDAwMUU3Zl19eABxAH4AFHNxAH4AAHNx
            AH4AA3VxAH4ABgAAAAZxAH4ACHEAfgAJcQB+AApxAH4AC3EAfgAMcQB+AA11cQB+AAYAAAAGcQB+
            AA9zcQB+ABAAABFYdAAbbWluZWNyYWZ0Om11c2ljX2Rpc2NfYmxvY2tzcQB+ABRzcQB+ABU/QAAA
            AAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAciQXJlYXMidAAbbWluZWNy
            YWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAAXe2Zsb2F0czpbMS4wMDAwMDAxRTdmXX14AHEAfgAUc3EA
            fgAAc3EAfgADdXEAfgAGAAAABnEAfgAIcQB+AAlxAH4ACnEAfgALcQB+AAxxAH4ADXVxAH4ABgAA
            AAZxAH4AD3NxAH4AEAAAEVh0ABltaW5lY3JhZnQ6bXVzaWNfZGlzY193YWl0cQB+ABRzcQB+ABU/
            QAAAAAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAkiUGxheWVycyJ0ABtt
            aW5lY3JhZnQ6Y3VzdG9tX21vZGVsX2RhdGF0ABd7ZmxvYXRzOlsxLjAwMDAwMDFFN2ZdfXgAcQB+
            ABRzcQB+AABzcQB+AAN1cQB+AAYAAAAGcQB+AAhxAH4ACXEAfgAKcQB+AAtxAH4ADHEAfgANdXEA
            fgAGAAAABnEAfgAPc3EAfgAQAAARWHQAGG1pbmVjcmFmdDptdXNpY19kaXNjX2NhdHEAfgAUc3EA
            fgAVP0AAAAAAAAx3CAAAABAAAAACdAAVbWluZWNyYWZ0OmN1c3RvbV9uYW1ldAAIIkJpb21lcyJ0
            ABttaW5lY3JhZnQ6Y3VzdG9tX21vZGVsX2RhdGF0ABd7ZmxvYXRzOlsxLjAwMDAwMDFFN2ZdfXgA
            cQB+ABRzcQB+AABzcQB+AAN1cQB+AAYAAAAGcQB+AAhxAH4ACXEAfgAKcQB+AAtxAH4ADHEAfgAN
            dXEAfgAGAAAABnEAfgAPc3EAfgAQAAARWHQAGW1pbmVjcmFmdDptdXNpY19kaXNjX21hbGxxAH4A
            FHNxAH4AFT9AAAAAAAAMdwgAAAAQAAAAAnQAFW1pbmVjcmFmdDpjdXN0b21fbmFtZXQACSJQcmVz
            ZXRzInQAG21pbmVjcmFmdDpjdXN0b21fbW9kZWxfZGF0YXQAF3tmbG9hdHM6WzEuMDAwMDAwMUU3
            Zl19eABxAH4AFHNxAH4AAHNxAH4AA3VxAH4ABgAAAAZxAH4ACHEAfgAJcQB+AApxAH4AC3EAfgAM
            cQB+AA11cQB+AAYAAAAGcQB+AA9zcQB+ABAAABFYdAAYbWluZWNyYWZ0Omdsb3dzdG9uZV9kdXN0
            cQB+ABRzcQB+ABU/QAAAAAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAoi
            Q2lyY3VpdHMidAAbbWluZWNyYWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAARe2Zsb2F0czpbMTMwLjBm
            XX14AHEAfgAUcHBwcHBwcHBwcHBwcHBwcHNxAH4AAHNxAH4AA3VxAH4ABgAAAAZxAH4ACHEAfgAJ
            cQB+AApxAH4AC3EAfgAMcQB+AA11cQB+AAYAAAAGcQB+AA9zcQB+ABAAABFYdAAabWluZWNyYWZ0
            Om11c2ljX2Rpc2NfY2hpcnBxAH4AFHNxAH4AFT9AAAAAAAAMdwgAAAAQAAAAAnQAFW1pbmVjcmFm
            dDpjdXN0b21fbmFtZXQACSJTYXZlcyAxInQAG21pbmVjcmFmdDpjdXN0b21fbW9kZWxfZGF0YXQA
            F3tmbG9hdHM6WzEuMDAwMDAwMUU3Zl19eABxAH4AFHBwcHNxAH4AAHNxAH4AA3VxAH4ABgAAAAZx
            AH4ACHEAfgAJcQB+AApxAH4AC3EAfgAMcQB+AA11cQB+AAYAAAAGcQB+AA9zcQB+ABAAABFYdAAO
            bWluZWNyYWZ0OmJvd2xxAH4AFHNxAH4AFT9AAAAAAAAMdwgAAAAQAAAAAnQAFW1pbmVjcmFmdDpj
            dXN0b21fbmFtZXQACyJOZXh0IFBhZ2UidAAbbWluZWNyYWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAAQ
            e2Zsb2F0czpbODYuMGZdfXgAcQB+ABRwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHA=
            """),

    SAVE_2("Save Storage 2", "saves_two", """
            rO0ABXcEAAAANnNyABpvcmcuYnVra2l0LnV0aWwuaW8uV3JhcHBlcvJQR+zxEm8FAgABTAADbWFw
            dAAPTGphdmEvdXRpbC9NYXA7eHBzcgA1Y29tLmdvb2dsZS5jb21tb24uY29sbGVjdC5JbW11dGFi
            bGVNYXAkU2VyaWFsaXplZEZvcm0AAAAAAAAAAAIAAkwABGtleXN0ABJMamF2YS9sYW5nL09iamVj
            dDtMAAZ2YWx1ZXNxAH4ABHhwdXIAE1tMamF2YS5sYW5nLk9iamVjdDuQzlifEHMpbAIAAHhwAAAA
            BnQAAj09dAALRGF0YVZlcnNpb250AAJpZHQABWNvdW50dAAKY29tcG9uZW50c3QADnNjaGVtYV92
            ZXJzaW9udXEAfgAGAAAABnQAHm9yZy5idWtraXQuaW52ZW50b3J5Lkl0ZW1TdGFja3NyABFqYXZh
            LmxhbmcuSW50ZWdlchLioKT3gYc4AgABSQAFdmFsdWV4cgAQamF2YS5sYW5nLk51bWJlcoaslR0L
            lOCLAgAAeHAAABFYdAAabWluZWNyYWZ0Om11c2ljX2Rpc2NfY2hpcnBzcQB+ABAAAAABc3IAF2ph
            dmEudXRpbC5MaW5rZWRIYXNoTWFwNMBOXBBswPsCAAFaAAthY2Nlc3NPcmRlcnhyABFqYXZhLnV0
            aWwuSGFzaE1hcAUH2sHDFmDRAwACRgAKbG9hZEZhY3RvckkACXRocmVzaG9sZHhwP0AAAAAAAAx3
            CAAAABAAAAACdAAVbWluZWNyYWZ0OmN1c3RvbV9uYW1ldAAHIlNhdmVzInQAG21pbmVjcmFmdDpj
            dXN0b21fbW9kZWxfZGF0YXQAF3tmbG9hdHM6WzEuMDAwMDAwMUU3Zl19eABxAH4AFHNxAH4AAHNx
            AH4AA3VxAH4ABgAAAAZxAH4ACHEAfgAJcQB+AApxAH4AC3EAfgAMcQB+AA11cQB+AAYAAAAGcQB+
            AA9zcQB+ABAAABFYdAAbbWluZWNyYWZ0Om11c2ljX2Rpc2NfYmxvY2tzcQB+ABRzcQB+ABU/QAAA
            AAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAciQXJlYXMidAAbbWluZWNy
            YWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAAXe2Zsb2F0czpbMS4wMDAwMDAxRTdmXX14AHEAfgAUc3EA
            fgAAc3EAfgADdXEAfgAGAAAABnEAfgAIcQB+AAlxAH4ACnEAfgALcQB+AAxxAH4ADXVxAH4ABgAA
            AAZxAH4AD3NxAH4AEAAAEVh0ABltaW5lY3JhZnQ6bXVzaWNfZGlzY193YWl0cQB+ABRzcQB+ABU/
            QAAAAAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAkiUGxheWVycyJ0ABtt
            aW5lY3JhZnQ6Y3VzdG9tX21vZGVsX2RhdGF0ABd7ZmxvYXRzOlsxLjAwMDAwMDFFN2ZdfXgAcQB+
            ABRzcQB+AABzcQB+AAN1cQB+AAYAAAAGcQB+AAhxAH4ACXEAfgAKcQB+AAtxAH4ADHEAfgANdXEA
            fgAGAAAABnEAfgAPc3EAfgAQAAARWHQAGG1pbmVjcmFmdDptdXNpY19kaXNjX2NhdHEAfgAUc3EA
            fgAVP0AAAAAAAAx3CAAAABAAAAACdAAVbWluZWNyYWZ0OmN1c3RvbV9uYW1ldAAIIkJpb21lcyJ0
            ABttaW5lY3JhZnQ6Y3VzdG9tX21vZGVsX2RhdGF0ABd7ZmxvYXRzOlsxLjAwMDAwMDFFN2ZdfXgA
            cQB+ABRzcQB+AABzcQB+AAN1cQB+AAYAAAAGcQB+AAhxAH4ACXEAfgAKcQB+AAtxAH4ADHEAfgAN
            dXEAfgAGAAAABnEAfgAPc3EAfgAQAAARWHQAGW1pbmVjcmFmdDptdXNpY19kaXNjX21hbGxxAH4A
            FHNxAH4AFT9AAAAAAAAMdwgAAAAQAAAAAnQAFW1pbmVjcmFmdDpjdXN0b21fbmFtZXQACSJQcmVz
            ZXRzInQAG21pbmVjcmFmdDpjdXN0b21fbW9kZWxfZGF0YXQAF3tmbG9hdHM6WzEuMDAwMDAwMUU3
            Zl19eABxAH4AFHNxAH4AAHNxAH4AA3VxAH4ABgAAAAZxAH4ACHEAfgAJcQB+AApxAH4AC3EAfgAM
            cQB+AA11cQB+AAYAAAAGcQB+AA9zcQB+ABAAABFYdAAYbWluZWNyYWZ0Omdsb3dzdG9uZV9kdXN0
            cQB+ABRzcQB+ABU/QAAAAAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9tX25hbWV0AAoi
            Q2lyY3VpdHMidAAbbWluZWNyYWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAARe2Zsb2F0czpbMTMwLjBm
            XX14AHEAfgAUcHBwcHBwcHBwcHBwc3EAfgAAc3EAfgADdXEAfgAGAAAABnEAfgAIcQB+AAlxAH4A
            CnEAfgALcQB+AAxxAH4ADXVxAH4ABgAAAAZxAH4AD3NxAH4AEAAAEVh0AA5taW5lY3JhZnQ6Ym93
            bHEAfgAUc3EAfgAVP0AAAAAAAAx3CAAAABAAAAACdAAVbWluZWNyYWZ0OmN1c3RvbV9uYW1ldAAP
            IlByZXZpb3VzIFBhZ2UidAAbbWluZWNyYWZ0OmN1c3RvbV9tb2RlbF9kYXRhdAAQe2Zsb2F0czpb
            ODcuMGZdfXgAcQB+ABRwcHBzcQB+AABzcQB+AAN1cQB+AAYAAAAGcQB+AAhxAH4ACXEAfgAKcQB+
            AAtxAH4ADHEAfgANdXEAfgAGAAAABnEAfgAPc3EAfgAQAAARWHQAGm1pbmVjcmFmdDptdXNpY19k
            aXNjX2NoaXJwcQB+ABRzcQB+ABU/QAAAAAAADHcIAAAAEAAAAAJ0ABVtaW5lY3JhZnQ6Y3VzdG9t
            X25hbWV0AAkiU2F2ZXMgMiJ0ABttaW5lY3JhZnQ6Y3VzdG9tX21vZGVsX2RhdGF0ABd7ZmxvYXRz
            OlsxLjAwMDAwMDFFN2ZdfXgAcQB+ABRwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBw
            """);

    final String title;
    final String table;
    final String empty;

    Storage(String title, String table, String empty) {
        this.title = title;
        this.table = table;
        this.empty = empty;
    }

    public String getTitle() {
        return title;
    }

    public String getTable() {
        return table;
    }

    public String getEmpty() {
        return empty;
    }
}
